CREATE TABLE role (
             person_id integer not null,
             roles varchar(5) );

CREATE TABLE person (
             person_id integer generated by default as identity,
             email_person varchar(128),
             login_person varchar(32) not null,
             name_person varchar(75),
             password_person varchar(16) not null,
             primary key (person_id) );

CREATE TABLE answer (
             answer_id integer generated by default as identity,
             name_answer varchar(16) not null,
             text_answer varchar(1025) not null,
             question_id integer not null,
             primary key (answer_id) );

CREATE TABLE qtype (
             qtype_id integer generated by default as identity,
             name_qtype varchar(5) not null,
             primary key (qtype_id) );

CREATE TABLE qtype_questions (
             qtype_qtype_id integer not null,
             questions_question_id integer not null );

CREATE TABLE question (
             question_id integer generated by default as identity,
             name_question varchar(1024),
             qtype_id integer not null,
             qvariant_id integer not null,
             primary key (question_id) );

CREATE TABLE question_answers (
             question_question_id integer not null,
             answers_answer_id integer not null );

CREATE TABLE question_question_variants (
             question_question_id integer not null,
             question_variants_qvariant_id integer not null );

CREATE TABLE qvariant (
             qvariant_id integer generated by default as identity,
             name_qvariant varchar(16) not null,
             answer_id integer not null,
             primary key (qvariant_id) );

CREATE TABLE survey (
             survey_id integer generated by default as identity,
             description_survey varchar(4096),
             finish_survey timestamp not null,
             start_survey timestamp not null,
             title_survey varchar(1024) not null,
             primary key (survey_id) );

CREATE TABLE survey_questions (
             survey_survey_id integer not null,
             questions_question_id integer not null );

ALTER TABLE person
            add constraint UK_1vuggdyxf7m5qn7jmocfioxg8 unique (login_person);

ALTER TABLE qtype_questions
            add constraint UK_h9wvcef7hqtj8l17mgobx2qft unique (questions_question_id);

ALTER TABLE question_answers
            add constraint UK_pqtu314fua658gijgv1o0fkb3 unique (answers_answer_id);

ALTER TABLE question_question_variants
            add constraint UK_rshta3h40nsdr3gxp4ir591hn unique (question_variants_qvariant_id);

ALTER TABLE survey
            add constraint UK_9tyuyskm8rj8jv1bok9xu85fp unique (title_survey);

ALTER TABLE survey_questions
            add constraint UK_sfgev5av62lk3ov6e5qbx2qof unique (questions_question_id);

ALTER TABLE answer
            add constraint FK8frr4bcabmmeyyu60qt7iiblo foreign key (question_id) references question;

ALTER TABLE qtype_questions
            add constraint FKa7akhhdu3gmcfu41eedv4ae5h foreign key (questions_question_id) references question;

ALTER TABLE qtype_questions
            add constraint FK2v4gw5c2fywbst2hfsxlbqv6m foreign key (qtype_qtype_id) references qtype;

ALTER TABLE question
            add constraint FKcxybfsr1qsbofhqnx43vuouvg foreign key (qtype_id) references qtype;

ALTER TABLE question
            add constraint FKjm4gbwec9o18htxvfpo2yhg1m foreign key (qvariant_id) references survey;

ALTER TABLE question_answers
            add constraint FKt7enohshub7lpbjx5b6mqc8ev foreign key (answers_answer_id) references answer;

ALTER TABLE question_answers
            add constraint FKoirfwv5qfap3s57ywao12s2eh foreign key (question_question_id) references question;

ALTER TABLE question_question_variants
            add constraint FKjxpcn5sn8as8m8cldf6ouwbnc foreign key (question_variants_qvariant_id) references qvariant;

ALTER TABLE question_question_variants
            add constraint FKe2xnb6wxc5yuy8kp4y01oo4x9 foreign key (question_question_id) references question;

ALTER TABLE qvariant
            add constraint FKnxyp5m88nrjuyvfnhm0r7tb8e foreign key (answer_id) references question;

ALTER TABLE role
            add constraint FKp74rfg21c55d8eebfl00w5451 foreign key (person_id) references person;

ALTER TABLE survey_questions
            add constraint FKcbgw5nk1a6xxwo6hi463iu4sb foreign key (questions_question_id) references question;

ALTER TABLE survey_questions
            add constraint FKsu5uj0v39bs01tgfv0i6718vl foreign key (survey_survey_id) references survey;

