CREATE TABLE person(
	person_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	email_person VARCHAR(128),
	login_person VARCHAR(32) NOT NULL,
	name_person VARCHAR(75),
	password_person varchar(16) NOT NULL,
	PRIMARY KEY (person_id));

CREATE TABLE role_id(
	person_id INTEGER not null,
	roles VARCHAR(8));

CREATE TABLE survey (
	survey_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	description_survey VARCHAR(4096),
	finish_survey TIMESTAMP,
	start_survey TIMESTAMP,
	title_survey VARCHAR(1024),
	PRIMARY KEY (survey_id));

ALTER TABLE person
	ADD constraint UK_1vuggdyxf7m5qn7jmocfioxg8 UNIQUE (login_person);

ALTER TABLE role_id
	ADD constraint FKgxedg62eugq0flc5fgegvby09 FOREIGN KEY (person_id) REFERENCES person