create table answer (
             answer_id integer generated by default as identity,
             participation_id integer not null,
             text_answer varchar(1025) not null,
             value_answer varchar(16) not null,
             primary key (answer_id) );

create table participation (
             participation_id integer generated by default as identity,
             person_id integer not null,
             question_id integer not null,
             survey_id integer not null,
             primary key (participation_id) );

create table person (
             person_id integer generated by default as identity,
             email_person varchar(128),
             login_person varchar(32) not null,
             name_person varchar(75),
             password_person varchar(16) not null,
             primary key (person_id) );

create table question (
             question_id integer generated by default as identity,
             type_question varchar(5),
             name_question varchar(1024),
             survey_id integer not null,
             primary key (question_id) );

create table question_question_variants (
             question_question_id integer not null,
             question_variants_qvariant_id integer not null );

create table qvariant (
             qvariant_id integer generated by default as identity,
             title_qvariant varchar(16) not null,
             value_qvariant varchar(16) not null,
             answer_id integer not null,
             primary key (qvariant_id) );

create table role (
             person_id integer not null,
             roles varchar(5) );

create table survey (
             survey_id integer generated by default as identity,
             description_survey varchar(4096),
             finish_survey timestamp not null,
             start_survey timestamp not null,
             title_survey varchar(1024) not null,
             primary key (survey_id) );

create table survey_questions (
             survey_survey_id integer not null,
             questions_question_id integer not null );

alter table person add constraint UK_1vuggdyxf7m5qn7jmocfioxg8 unique (login_person);

alter table question_question_variants add constraint UK_rshta3h40nsdr3gxp4ir591hn unique (question_variants_qvariant_id);

alter table survey add constraint UK_9tyuyskm8rj8jv1bok9xu85fp unique (title_survey);

alter table survey_questions add constraint UK_sfgev5av62lk3ov6e5qbx2qof unique (questions_question_id);

alter table question add constraint FK65ro96jafjvulbqu8ia0pb254 foreign key (survey_id) references survey;

alter table question_question_variants add constraint FKjxpcn5sn8as8m8cldf6ouwbnc
            foreign key (question_variants_qvariant_id) references qvariant;

alter table question_question_variants add constraint FKe2xnb6wxc5yuy8kp4y01oo4x9
            foreign key (question_question_id) references question;

alter table qvariant add constraint FKnxyp5m88nrjuyvfnhm0r7tb8e foreign key (answer_id) references question;

alter table role add constraint FKp74rfg21c55d8eebfl00w5451 foreign key (person_id) references person;

alter table survey_questions add constraint FKcbgw5nk1a6xxwo6hi463iu4sb
            foreign key (questions_question_id) references question;

alter table survey_questions add constraint FKsu5uj0v39bs01tgfv0i6718vl
            foreign key (survey_survey_id) references survey
